# Generated by Django 5.0 on 2023-12-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_openinghours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='openingHours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='store.openinghours'),
        ),
    ]
