# Generated by Django 5.0 on 2023-12-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_openinghours_delete_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='store.address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='openingHours',
            field=models.CharField(choices=[('00:06 AM', '00:06 AM'), ('00:09 AM', '00:09 AM'), ('00:12 PM', '00:12 PM')], max_length=200),
        ),
    ]
