# Generated by Django 5.0 on 2023-12-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_store_food_remove_store_openinghours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='branch',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
